### ISSUE TITLE
No validation results?

### ISSUE THREAD

**Issue by YubinXie** [HzFu/REFUGE_baseline#1]
I did not see results of Evaluation on Validation Data.

**Comment by emma-sjwang** [comment]
When will release?

**Comment by HzFu** [comment]
Hi, we have updated the validation result, as:

*MNet Result:*
> Evaluating segmentation results
Dice Optic Cup = 0.8704837907032029
Dice Optic Disc = 0.9124488019916737
MAE CDR = 0.049007256208688184
> Evaluating classification results
AUC = 0.9630555555555557
Reference Sensitivity = 0.9

*DENet Result:*
> Evaluating classification results
AUC = 0.7722222222222221
Reference Sensitivity = 0.6357142857142858

**Comment by emma-sjwang** [comment]
So high....

**Comment by YubinXie** [comment]
Thank you. I assume the this result is trained on ORIGA650. Do you have validation results that trained on your own training data? For a fair comparison. Thanks!

**Comment by HzFu** [comment]
Yes, this result is trained on ORIGA650. Currently, we did not have validation result trained on REFUGE training data.
